version: '3.8'
services:
  mysqldb:
    image: mysql:8.0
    container_name: cruddemo_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: student_tracker
      MYSQL_USER: springstudent
      MYSQL_PASSWORD: springstudent
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    build: .
    container_name: cruddemo_app
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/student_tracker?useSSL=false&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: springstudent
      SPRING_DATASOURCE_PASSWORD: springstudent
      SPRING_PROFILES_ACTIVE: prod

volumes:
  db_data:
