spring.application.name=cruddemo
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# Turn off Spring Boot Banner
spring.main.banner-mode=off

# Production logging level
logging.level.root=warn
logging.level.org.hibernate.SQL=warn

# JPA properties
spring.jpa.hibernate.ddl-auto=update
